server:
  port: 8091

spring:
  application:
    name: wheatmall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        register-enabled: true

logging:
  level:
    com.wheatmall.product: debug
