server:
  port: 8090

spring:
  application:
    name: wheatmall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        register-enabled: true

logging:
  level:
    com.wheatmall.order: debug
