server:
  port: 8090

spring:
  application:
    name: wheatmall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        register-enabled: true

logging:
  file:
    path: /tmp  # 所有日志（包括Nacos）都会输出到 /tmp 目录
  level:
    com.wheatmall.order: debug

nacos:
  logging:
    path: /tmp/nacos  # 专门指定nacos日志路径